export const products = [
  {
    id: 1,
    name: "Men's Turbine Long Sleeve Tee",
    price: '$45',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's Turbine Long Sleeve Tee",
  },
  {
    id: 2,
    name: "Men's Turbine Short Sleeve Tee",
    price: '$40',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's Turbine Short Sleeve Tee",
  },
  {
    id: 3,
    name: "Men's Chill Crew Neck Sweatshirt",
    price: '$75',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's Chill Crew Neck Sweatshirt",
  },
  {
    id: 4,
    name: "Men's Raven Lightweight Zip Up Bomber Jacket",
    price: '$130',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's Raven Lightweight Zip Up Bomber Jacket",
  },
  {
    id: 5,
    name: "Men's Solar Roof Tee",
    price: '$35',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's Solar Roof Tee",
  },
  {
    id: 6,
    name: "Men's 3D T Logo Tee",
    price: '$35',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's 3D T Logo Tee",
  },
  {
    id: 7,
    name: "Men's Battery Day Tee",
    price: '$35',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's Battery Day Tee",
  },
  {
    id: 8,
    name: "Men's Cybertruck Bulletproof Tee",
    price: '$35',
    imageSrc: 'https://placehold.it/500x500',
    imageAlt: "Men's Cybertruck Bulletproof Tee",
  },
];
